### ISSUE TITLE
Integration of `analyzer`

### ISSUE THREAD

**Issue by malemi** [GetJenny/starchat#44]
## Scope

We want to make possible for *chat developers to –

1. add NLP capabilities (e.g. at the moment we are using elasticsearch to identify the state from the user's query, but someone might want to use Neural Networks)
2. integrate *chat with other services

## Add NLP capabilities

For this, the `analyzer` package was developed. It has two main components: Atomic and Analyzers

### Atomic

Atomic are objects computing the likelihood that the user wants to go to the state. They are _instantiated_ with a significant and compute how close the user's query is to that. E.g., we can build instantiate the `forgotPassSimilar` Atomic to characterise the state `forgot_password`:

```scala
val forgotPassSimilar  = new W2VCosineSentenceAtomic(sentence = "I forgot my password")
```

In this way, when a user enters "I cannot find my password", `forgotPassSimilar.evaluate("I cannot find my password")` will output a normalised score telling how likely the user was meaning they forgot their password.

### Analyzer

Analyzers are "aggregators of atomics". The default one, which comes with a parser, allows the person in charge of configuring *chat to easily concatenate atomics. For instance, if the we want the user to go into state "forgot_password" whenever all this conditions are satisfied:

* there is the word "password"
* there is: either the word "forgot" or the word "lost" or a synonym of the word "problem"

we write something like that:

`conjunction(disjunction(keyword("forgot"), keyword("lost"), synonym("problem")), keyword("password")))`

into the configuration file's "analyzer" field.

### The `atomic search`

Because we have used Elasticsearch till now, and we believe it is and will be an excellent tool for having *chat working with relatively little effort, the atomic search –which uses Elasticsearch– can be implemented in a slightly different way. Best to start on how can be used by the developer.

A configuration file using Elasticsearch and W2VCosineSentenceAtomic would looks like that:

|state|...|analyzer|queries |...|
|-----|--|--------|--------|--|
|forgot_password|...|conjunction(search(), similar("forgot password"))|"[""I cannot find password"", ""cannot remember password""]"|...|

This means "compute the likelihood that _either_ the user was searching for `"I cannot find password" or "cannot remember password"`, _or_ that the user's query was close to `"forgot password"` (as computed by cosine similarity with w2v).

This means that when *chat is initialised:

* an object of type `StarchatAnalyzer` is instantiated, with the string in the CSV field "analyzer" as parameter. In this way, the parser will:
   * instantiate an object of type W2VCosineSentenceAtomic
   * instantiate an object of type `searchAtomic`. This object will take  as parameter –it depends on @angleto :) – 
      * either `"""["I cannot find password", "cannot remember password"]"""`
      * or `forgot_password` (because of how we index all queries, the state ID is returned when we search for a sentence)
* all sentences in the CSV field "queries" are indexed with the correspondent state ID

When the user enters the sentence "where is my password", the StarchatAnalyzer for the field "forgot_password" will, through `.evaluate("where is my password")`:

* run `forgotPassSimilar.evaluate("where is my password")`
* run  `forgotPassSearch.evaluate("where is my password")`
* compute and return the disjunction likelihood

**Comment by angleto** [comment]
The analyzer branch was merged into master. This ticket can be closed.
