### ISSUE TITLE
Add port as parameter in shellscripts

### ISSUE THREAD

**Issue by Malmarim** [GetJenny/starchat#59]
As we run multiple starchats paralel, it would save a lot of time if all the scripts in /scripts/api_test would accept port as a parameter. For example with getNextResponseSearch.sh

QUERY=${1:-"cannot access account"}
PORT=${2:-8888}
curl -v -H "Content-Type: application/json" -X POST http://localhost:${PORT}/get_next_response -d

**Comment by angleto** [comment]
fix merged, thanks @olandere
