### ISSUE TITLE
How to install knowledge base ?

### ISSUE THREAD

**Issue by deepiksdev** [GetJenny/starchat#64]
We'd like to test the whole conversation engine and possibly create an integration in our [advanced open source chatbot platform](https://github.com/deepiksdev/node).

In the [documentation](https://getjenny.github.io/starchat-doc/#configuration-of-the-answer-recommender-knowledge-base) , instructions are still missing about how to install the knowledge base feature. Can you explain how this should be installed ?

**Comment by malemi** [comment]
hey @deepiksdev , thanks for that, you're right! We'll do it soon and keep you posted, ok?

**Comment by malemi** [comment]
hey, have a look at the [doc](https://getjenny.github.io/starchat-doc/#configuration-of-the-answer-recommender-knowledge-base).

We are going to improve it, but in the meantime let us know if you have problems! Cheers

**Comment by malemi** [comment]
see  https://github.com/deepiksdev/starchat/issues/1
