### ISSUE TITLE
Issues with CORS headers

### ISSUE THREAD

**Issue by jlumme** [GetJenny/starchat#66]
Hi! I'm having a hard time getting starchat integrated to our solution. With curl 
`curl -v -H "Content-Type: application/json" -X POST http://127.0.0.1:8888/knowledgebase_search -d '{
  "question": "thank you",
  "verified": true,
  "doctype": "normal"
}'`

I get a correct response from the service but when I'm trying to call it inside our node application I have problems with CORS headers in the response. Is there some way to configure correct headers?

`XMLHttpRequest cannot load http://127.0.0.1:8888/get_next_response. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://staging' is therefore not allowed access. The response had HTTP status code 405.`

**Comment by malemi** [comment]
Hello @jlumme! Thanks for your feedback. We'll try to reproduce the issue on our side and get back to you ASAP

**Comment by Malmarim** [comment]
Hey @jlumme, can you describe how are you calling Starchat to get the issue?

**Comment by jlumme** [comment]
Currently I'm just using dummydata and copied the ajax usage from starchat demo
`import ajax from 'superagent'`

```
    ajax
      .post('http://127.0.0.1:8888/knowledgebase_search')
      .send({ "question": "thank you", "verified": true, "doctype": "normal" })
      .withCredentials()
      .set('Accept', 'application/json')
      .end(function (err, res) {
          if (err) {
            console.log('Error.', err);
          } else {
            console.log(res)
          }
     })
```
I get the same cors error if I turn on the ssl from starchat

**Comment by angleto** [comment]
Is this ajax call executed on the browser? If so, the browser will block the call because StarChat does not handle CORS requests, because StarChat should not be exposed on the frontend and the APIs should be called only by the backend.

**Comment by jlumme** [comment]
Ahh, of course, this was a stupid mistake on my part :slightly_smiling_face: I made a NodeJS handler to get past the cors issues. Thanks!

**Comment by angleto** [comment]
Thanks.
I close the ticket.
