### ISSUE TITLE
Control the answers given by knowledgebase

### ISSUE THREAD

**Issue by jlumme** [GetJenny/starchat#69]
The problem I'm running into is that we have multiple "teams" which each need their own answers. Those answers between teams can't get mixed up.

The only way I have currently figured out how to "scale" the application to get different answers is to make different starchat and Manaus containers for each team, which is quite a heavy load for our current usage.

Is there any way to use for example the topics when querying the database for answers?

**Comment by angleto** [comment]
The topics are not exposed to search at the moment, they will be used for another kind of descriptions. 

The solutions are:
1.  Use the "doctype" field and add the class of data e.g.: "normal group0" note that "doctype" do an exact match, so the ordering matter. This means that you must specify the same string indexed "group0 normal" will not match. 
2.  We already planned to add a "class" field on the Knowledgebase (similar to topics) for this specific need, if you want to contribute and add this field it would be great.

**Comment by angleto** [comment]
I added the optional field "dclass" and the possibility to query using this field, this is exactly what you need.
After the pull request is merged the new functionality will be available on the master branch: https://github.com/GetJenny/starchat/pull/70

**Comment by jlumme** [comment]
Thanks! This will help us a lot going forward with starchat :slightly_smiling_face:

**Comment by angleto** [comment]
merged the improvement into the master branch and v3.0
