### ISSUE TITLE
traversed_states array does not include fetched states

### ISSUE THREAD

**Issue by tomimick** [GetJenny/starchat#77]
If I ask a query that results into a (button) action, and then click a button, the next reply from SC (fetched with return_value=statename) does not have the latter state added in the traversed states array. Is this intentional?

**Comment by angleto** [comment]
Initially is was an intentional behaviour to allow to enter again the same state using the lastTraversedState analyzer. Anyway is correct that if a state was requested it should be included into the list of traversed states.
Fixed on tag v3.0.3
