### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [GetJenny/starchat#91]
Hi @GetJenny I am a graphics designer and would like to contribute by designing a nice logo for the project. I noticed it doesn't have one yet and i think it will be more interesting if it has a logo representation. If you will permit me i will begin designing asap. Thanks and best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by angleto** [comment]
Hello, sorry but this is an issue tracker specific for the software project, so is not the right place to contact us for commercial proposals.
Thanks.
